version: "3.3"
services:
  web:
    volumes:
      - ./:/var/www/app
    build: "./"
    command: sh -c 'yarn install && yarn start'
    environment:
      - NODE_ENV=development
      - PORT=5000
      - REDIS_URL=redis://redis-opencheck
    ports:
      - 5000:5000
    links:
      - redis
    depends_on:
      - redis
  redis:
    container_name: redis-opencheck
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
